[package]
name = "pocketstation-rs"
version = "0.1.0"
authors = ["Lionel Flandrin <lionel.flandrin@gmail.com>"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
